# Generated by Django 3.0.6 on 2020-05-13 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMainBanner',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='page_main_banner_pagemainbanner', serialize=False, to='cms.CMSPlugin')),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg'])])),
                ('heading', models.CharField(blank=True, default='', help_text='Enter heading', max_length=100)),
                ('description', models.CharField(blank=True, default='', help_text='Enter description', max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
